IATI/IATI-Codelists-NonEmbedded

- xml/CRSChannelCode.xml
Codes added:
* `11001` Central Government
* `11002` Local Government
* `11003` Public corporations
* `11004` Other public entities in donor country
* `12001` Central Government
* `12002` Local Government
* `12003` Public corporations
* `12004` Other public entities in recipient country
* `43006` Catastrophe Containment and Relief Trust
* `47143` Global Community Engagement and Resilience Fund
* `47144` International Renewable Energy Agency
* `60000` Private sector institution
* `61000` Private sector in provider country
* `61001` Private bank in provider country
* `61002` Private exporter in provider country
* `61003` Private investor in provider country
* `61004` Other non-bank entity in provider country
* `62000` Private sector in recipient country
* `62001` Private bank in recipient …
> Update CRSChannelCode codelist

- xml/Sector.xml
I’ve modified @bjwebb’s [convert.py](https://github.com/IATI/IATI-Codelists-NonEmbedded/blob/5f60c4fc/convert.py) code to generate an updated Sector codelist from:
https://andylolz.github.io/dac-crs-codes/
It looks like code 15114 may have been reused (previously “Tax policy and tax administration support”, now “Domestic Revenue Mobilisation”).
Also from [looking at the diff](https://github.com/IATI/IATI-Codelists-NonEmbedded/pull/137/files), it looks like the following new codes are added:
* `15180` Ending violence against women and girls
* `23110` Energy policy and administrative management
* `23181` Energy education/training
* `23182` Energy research
* `23183` Energy conservation and demand-side efficiency
* `23210` Energy generation, renewable sources – multiple technologies
* `23220` …
> Update Sector codelist

- xml/FlowType.xml
Codes added:
* `21` Non-export credit OOF
* `22` Officially supported export credits
* `36` Private Foreign Direct Investment
* `37` Other Private flows at market terms
Codes withdrawn:
* `20` OOF (I’m not exactly sure when… Between 2017-03-14 and 2017-03-17)
Codes modified:
* `35`: Name changed from ‘Private Market’ to ‘Private market’
> Update FlowType codelist

- xml/FileFormat.xml
I’ve used [get.sh](https://github.com/IATI/IATI-Codelists-NonEmbedded/blob/5f60c4fc/get.sh) and [convert.py](https://github.com/IATI/IATI-Codelists-NonEmbedded/blob/5f60c4fc/convert.py) to bring the [FileFormat codelist](http://iatistandard.org/202/codelists/FileFormat/) up to date.
I’ve marked a few codes as withdrawn where their names appeared to suggest that was the case.
> FileFormat updates

- xml/CRSChannelCode.xml
- xml/CollaborationType.xml
- xml/Region.xml
- xml/Sector.xml
- xml/SectorCategory.xml
Latest round of codelist updates from the DAC.
* Add “Conservation International” (`21063`)
* Add “National Red Cross and Red Crescent Societies” (`23501`)
* Add “UN-led Country-based Pooled Funds” (`41503`)
* Add “World Tourism Organization” (`41319`)
* Add “Asian Infrastructure Investment Bank” (`46026`)
* Add “Center of Excellence in Finance” (`47145`)
~~### Finance Type category~~
* ~~Add “NON FLOW ITEMS” (`0`)~~
~~### Finance Type~~
* ~~Add “GNI: Gross National Income” (`1`)~~
* ~~Add “ODA % GNI (`2`)~~
* ~~Add “Total flows % GNI” (`3`)~~
* ~~Add “Population” (`4`)~~
[UPDATE: #16 suggests these finance type codes should not be part of this update, so I have removed them.]
…And other assorted typos and corrections.
---
One thing to note: Sector.xml previously used tabs instead of …
> August 2017 DAC CRS codelist updates

- xml/Country.xml
This code is no longer part of the [ISO 3166-1 list](https://www.iso.org/iso-3166-country-codes.html), so marking as withdrawn.
> Mark ‘Netherland Antilles’ as withdrawn

- xml/RegionVocabulary.xml
> Add RegionVocabulary as a NE-Codelist

- xml/PolicyMarker.xml
> Add PolicyMarker as a NE-Codelist

- xml/PolicyMarkerVocabulary.xml
> Add PolicyMarkerVocabulary as a NE-Codelist

- xml/PublisherType.xml
> Add PublisherType as a NE-Codelist

- xml/ResultType.xml
> Add ResultType as a NE-Codelist

- xml/SectorVocabulary.xml
> Add SectorVocabulary as a NE-Codelist

- xml/OtherIdentifierType.xml
> Add OtherIdentifierType as a NE-Codelist

- xml/OrganisationType.xml
> Add OrganisationType as a NE-Codelist

- xml/IndicatorMeasure.xml
> Add IndicatorMeasure as a NE-Codelist

- xml/LoanRepaymentType.xml
> Add LoanRepaymentType as a NE-Codelist

- xml/GeographicVocabulary.xml
> Add GeographicVocabulary as a NE-Codelist

- xml/GeographicLocationReach.xml
> Add GeographicLocationReach as a NE-Codelist

- xml/DocumentCategory-category.xml
> Add DocumentCategory-category as a NE-Codelist

- xml/DisbursementChannel.xml
> Add DisbursementChannel as a NE-Codelist

- xml/DescriptionType.xml
> Add DescriptionType as a NE-Codelist

- xml/BudgetIdentifierVocabulary.xml
> Add BudgetIdentifierVocabulary as a NE-Codelist

- xml/OrganisationRegistrationAgency.xml
* Replace all ‘organization’s with ‘organisation’ (i.e. US -> UK spelling).
* Refer to ‘Organisation identifier list’ in the singular (because each codelist item refers to a list of organisation identifiers)
> Fix typos in OrganisationRegistrationAgency description

- xml/CRSChannelCode.xml
- xml/FlowType.xml
- xml/Sector.xml
DAC codelists were updated in December. I think this PR includes all of the changes.
NB this PR was generated using IATI/IATI-Codelists-NonEmbedded#172.
> December 2017 DAC codelist update

- xml/PolicyMarker.xml
- xml/PolicySignificance.xml
Refs https://discuss.iatistandard.org/t/where-does-the-policymarker-codelist-come-from/1298
> Add some policy marker-related metadata

- xml/Country.xml
Updating Country Codes to match the 'short name' on ISO Codelist.
Including changes to Libya, Palestine, Czechia, and other small changes.
> Updating Country Codes to match ISO Codelist

- xml/OrganisationRegistrationAgency.xml
Re: #248 - make this clearer that this is managed / sourced by org-id
@amy-silcock @PetyaKangalova @dalepotter sorry, I missed this commit in the set of PRs that were originally sent through.  Thanks to @andylolz for spotting!
> Update description text

- xml/BudgetIdentifierVocabulary.xml
Effective immediately! Fixes #240.
> Mark IATI budget identifier as withdrawn (v2.03 upgrade)

- xml/OrganisationRegistrationAgency.xml
hyperlink doesn’t render correctly without this.
> Typo: Add missing space

- xml/TagVocabulary.xml
Proposal to add SDG goals, targets and indicators to the non-embedded codelist tag vocabulary: https://discuss.iatistandard.org/t/add-sdg-goals-and-targets-to-the-tagvocabulary-codelist/1562
No objection so far.  Changes to be reviewed and merged by 4th of December.
> Adding SDG goals, targets, indicators to the TagVocabulary codelist

- xml/Currency.xml
As per https://www.currency-iso.org/dam/downloads/dl_currency_iso_amendment_168.pdf the new code VES replaces VEF per 2018-08-20
> Replace Venezualian Bolivar

- xml/PolicyMarker.xml
There are three new Policy Marker  in the [OECD DAC codelist](http://www.oecd.org/dac/stats/dacandcrscodelists.htm) updated on  (05/02/19)  that have not yet been replicated in IATI
> 3 new markers have been approved by the WP-STAT to be implemented in 2019 on 2018 flows:
> 1 mandatory: Disaster Risk Reduction DRR (DCD/DAC/STAT(2017)26)
> 2 voluntary : Disability (DCD/DAC/STAT(2018)39/REV1) and Nutrition (DCD/DAC/STAT(2018)38/REV1)
>  Three additions to the Policy Marker codelist

- xml/Country.xml
Updated from 'Macedonia (the former Yugoslav Republic of)' to 'North Macedonia'
> Update Country - Macedonia.xml

- xml/AidTypeVocabulary.xml
- xml/GeographicVocabulary.xml
- xml/PolicyMarkerVocabulary.xml
- xml/SectorVocabulary.xml
This forms part of the work to update IATI's codelist management processes. This PR points links to replicated codelists to the IATI URL, rather than the external source.
See: 
- https://github.com/IATI/IATI-Codelists-NonEmbedded/issues/293 
- https://github.com/IATI/IATI-Extra-Documentation/pull/552 
This also encompasses: https://github.com/IATI/IATI-Codelists-NonEmbedded/issues/272
> Point replicated codelists in iati vocabs to iati urls

- xml/AidTypeVocabulary.xml
Add new Aid Type vocabulary as per agreement on IATI discuss: https://discuss.iatistandard.org/t/approved-proposal-to-add-cash-transfer-and-voucher-codelist-under-aid-type-vocabulary/1793
@IATI/devs , please check if I have added the correct URL for code 4 as it needs to link to newly created codelist from pull request #309 .
> Add code 4 to AidTypeVocabulary codelist

- xml/CashandVoucherModalities.xml
As per IATI Discuss: https://discuss.iatistandard.org/t/approved-proposal-to-add-cash-transfer-and-voucher-codelist-under-aid-type-vocabulary/1793
My mistake for pasting wrong description first time round.
> Adding the correct description for code 2- Voucher

- xml/Sector.xml
- xml/SectorCategory.xml
These codes were removed as part of #283, because codelist values were taken directly from DAC XML. However, this DAC XML is missing a number of withdrawn codes, so these should be re-added.
As per the [codelist management page](http://reference.iatistandard.org/203/codelists-guides/codelist-management/#non-embedded-codelists-replicated), Withdrawn codes are **never** removed from replicated codelists. So this should be addressed as a bugfix.
> BUGFIX: Re-add withdrawn codes

- xml/EarmarkingCategory.xml
This is the only camel-cased codelist name, so I guess this is a typo.
> Add missing space in EarmarkingCategory name

- xml/CRSChannelCode.xml
- xml/Region.xml
Here is the updated Channel Code codelist from the OECD XML file as updated on May 5, 2020. As far as I can tell, the XML only contains one additional code (`41151`) and all of the other modifications are simply changes to withdrawn/active status and activation-dates.
> Channel code update from 2020/05/05 OECD XML file

- xml/AidType-category.xml
- xml/CRSChannelCode.xml
- xml/CollaborationType.xml
- xml/FinanceType-category.xml
- xml/FinanceType.xml
- xml/Sector.xml
- xml/SectorCategory.xml
At one point we had commented out the code that removed empty narratives to reduce the noise in the GitHub diff. My guess is that this was being done at the same time as a DAC Codelist update and that work took prescendence.
Now we've just completed a DAC Codelist update so the only change here will be removing the empty narrative elements. So next time we do a DAC codelist update we can leave the empty narratives out.﻿
> remove empty narratives

- xml/CRSChannelCode.xml
Synced by https://github.com/IATI/DAC-Codelists/pull/12 (see note there about the date modified).
Changes:
* 1 code withdrawn 21508 (Sustainable Energy for All).
* 1 code added 43007 (IMF’s Resilience and Sustainability Trust)
* 9 descriptions changed
> Update OECD DAC Codelists with 2023-08-29 changes

- xml/UNSDG-Goals.xml
This pull request includes a correction to the French translation of Goal 8 in the `xml/UNSDG-Goals.xml` file. The narrative now accurately reflects the content of Goal 8. 
* [`xml/UNSDG-Goals.xml`](diffhunk://#diff-158ca9060b70611c4a60412435ad643609dc6a0857c5149e30f6b5e42d8afc53L68-R68): Updated the French narrative for Goal 8 to correctly describe "Promouvoir une croissance économique soutenue, partagée et durable, le plein emploi productif et un travail décent pour tous" instead of incorrectly referencing Goal 7.
> Translate UNSDG goal 8
