xml/OrganisationRegistrationAgency.xml
=> [#45] Updates link for http://www.npo.gov.za/

xml/OrganisationRegistrationAgency.xml
There needs to be approval of this change before it is merged. See: http://support.iatistandard.org/entries/69301385-Proposal-for-UA-EDR-Ukraine-via-OCDS-
=> [#46] Adds entry for UA-EDR

xml/OrganisationRegistrationAgency.xml
Uses the narrative element to give names in two different languages
This is the first time we have done this.
Also please check the links work for you before accepting this change
=> [#47] Adds ES-DIR3 to the Regestration Agency list

xml/OrganisationRegistrationAgency.xml
Following instructions in the support forum:
http://support.iatistandard.org/entries/76840029-Add-Indian-Ministry-of-Corporate-Affairs
=> [#56] Adds IN-MCA to OrgRegistrationAgency list

xml/Country.xml, xml/Currency.xml
For change instructions please see http://www.currency-iso.org/en/shared/amendments/iso-4217-amendment.html. For the full ISO 4217 specification of countries and currencies, please see http://www.currency-iso.org/dam/downloads/lists/list_one.xml.
=> 20 08 2015 iso4217 update

xml/FlowType.xml
Please see the below for the DAC Flow type values used.
=> FlowType brought up to date with DAC

xml/FileFormat.xml, xml/IATIOrganisationIdentifier.xml, xml/Region.xml, xml/Version.xml
Accidentally included a codelist change in this push - shouldn't matter, but make sure that the UNM changes are merged beforehand to make sure that the changes aren't different!
=> 20 08 2015 typo correction

xml/OrganisationRegistrationAgency.xml
A branch for OrganisationRegistrationAgency codelist additions. Relates to [#91], [#93], and [#94].
=> 10 12 2015 codelist additions

xml/AidType-category.xml, xml/AidType.xml
This doesn’t do anything exciting – just updates some descriptions. Feel free to close if it’s not relevant.
=> Update AidType and AidTypeCategory codelists

xml/SectorCategory.xml
Codes added:
* `231` Energy generation, distribution and efficiency – general
* `232` Energy generation, renewable sources
* `233` Energy generation, non-renewable sources
* `234` Hybrid energy electric power plants
* `235` Nuclear energy electric power plants
* `236` Heating, cooling and energy distribution
Codes withdrawn:
* `230` ENERGY GENERATION AND SUPPLY
* `920` SUPPORT TO NON- GOVERNMENTAL ORGANISATIONS (NGOs)
Note that this doesn’t mark withdrawn codes as `status="withdrawn"`. They’re left untouched.
=> Update SectorCategory codelist

xml/AidType-category.xml, xml/AidType.xml, xml/CRSChannelCode.xml, xml/CollaborationType.xml, xml/FinanceType-category.xml, xml/FinanceType.xml, xml/Sector.xml, xml/SectorCategory.xml
Hopefully an exhaustive set of updates of DAC CRS codelists, including:
* Adding missing French translations
* Marking withdrawn codes as such
* Adding missing codes
=> DAC CRS codelist updates

xml/OrganisationRegistrationAgency.xml
See: https://discuss.iatistandard.org/t/approved-proposed-addition-to-the-organisation-registration-agency-codelist-palestine/931
=> [#164] Add code PS-MOI to OrganisationRegistrationAgency

xml/OrganisationRegistrationAgency.xml
Hi all,
I have now updated the text, following some useful suggestions from Tim. Please review and merge this pull request. Let me know if you have any questions.
Thanks,
Petya
=> Update OrganisationRegistrationAgency.xml with org-id.guide changes

xml/OrganisationRegistrationAgency.xml
Suggested change of the OrganisationRegistrationAgency codelist maintenance text, following the soft launch of the org-id.guide.
=> Update text to OrganisationRegistrationAgency codelist maintenance

xml/AidTypeVocabulary.xml, xml/BudgetNotProvided.xml, xml/ResultVocabulary.xml, xml/TagVocabulary.xml
Fixes https://github.com/IATI/IATI-Codelists-NonEmbedded/issues/183
Complete:
Fixes BudgetNotProvided https://github.com/IATI/IATI-Codelists-NonEmbedded/issues/184
Fixes AidTypeVocabulary https://github.com/IATI/IATI-Codelists-NonEmbedded/issues/185
Fixes ResultVocabulary https://github.com/IATI/IATI-Codelists-NonEmbedded/issues/181
Fixes https://github.com/IATI/IATI-Codelists-NonEmbedded/issues/178
=> Add 2.03 codelists

xml/TiedStatus.xml
=> Add TiedStatus as a NE-Codelist

xml/VerificationStatus.xml
=> Add VerificationStatus as a NE-Codelist

xml/LoanRepaymentPeriod.xml
=> Add LoanRepaymentPeriod as a NE-Codelist

xml/GeographicalPrecision.xml
=> Add GeographicalPrecision as a NE-Codelist

xml/GeographicExactness.xml
=> Add GeographicExactness as a NE-Codelist

xml/GeographicLocationClass.xml
=> Add GeographicLocationClass as a NE-Codelist

xml/ContactType.xml
=> Add ContactType as a NE-Codelist

xml/ConditionType.xml
=> Add ConditionType as a NE-Codelist

xml/CRSAddOtherFlags.xml
=> Add CRSAddOtherFlags as a NE-Codelist

xml/BudgetIdentifierSector-category.xml
=> Add BudgetIdentifierSector-category as a NE-Codelist

xml/BudgetIdentifier.xml
=> Add BudgetIdentifier as a NE-Codelist

xml/ActivityScope.xml
=> Add ActivityScope as a NE-Codelist

xml/BudgetIdentifierSector.xml
See IATI/IATI-Codelists#114
Fixes IATI/IATI-Codelists#91
=> Remove duplicate code from BudgetIdentifier

xml/AidTypeVocabulary.xml
This is as per comment in #185.
Fixes #185
=> Remove AidTypeVocabulary code 2

xml/IndicatorMeasure.xml
=> Add with-2.03 codes to IndicatorMeasure codelist

xml/OrganisationType.xml
=> Add with-2.03 codes to OrganisationType codelist

xml/BudgetNotProvided.xml
This brings it in line with #184 
Fixes #184
=> Fix BudgetNotProvided code name capitalisation

xml/AidTypeVocabulary.xml, xml/BudgetNotProvided.xml, xml/ResultVocabulary.xml, xml/TagVocabulary.xml
=> Fix metadata for new-for-2.03 NE-Codelists

CONTRIBUTING.rst
Add information about updating the changelog when modifying a Codelist.
=> Update CONTRIBUTING.rst - add changelog information

xml/IndicatorVocabulary.xml
With 2.03 going live, we are now adding SDG indicators- list following no objection to this post : https://discuss.iatistandard.org/t/proposed-addition-to-the-indicator-vocabulary-codelist/946/3
=> Adding SDG Indicators

xml/HumanitarianScopeVocabulary.xml
UN OCHA (Sean Foo) provided  us with an updated link to the  Humanitarian Plans that includes all plans for all years in an XML file.   I will now add to IATI discuss to inform the community.
=> Update URL for  Code 2-1 Humanitarian Plan

xml/OrganisationRegistrationAgency.xml
This is a copy and paste [of the XML](http://org-id.guide/download.xml) from [org-id.guide](http://org-id.guide), to bring the OrganisationRegistrationAgency codelist in line with it.
Refs #235.
=> Update org reg agency codelist from org-id.guide

xml/AidTypeVocabulary.xml
@Dale, I've added in descriptions and URL's for these. Please can you check these are okay. Can you also edit code 2 URL so that it updates the version automatically?
@Petya, Please can you add in the outstanding definitions and check the OECD DAC one (taken from the OECD DAC website)
=> Add codes to Aid Type Vocab

xml/EarmarkingCategory
As per this post: https://discuss.iatistandard.org/t/proposal-to-add-two-codes-on-earmarking-to-the-aidtype-vocabulary-codelist/1245
@dalepotter  Could you please check and approve this one?
=> Create Earmarking Category

xml/BudgetIdentifier.xml
Added a sentence referring to deprecation of codelist. References IATI/IATI-Extra-Documentation#481
=> Updated Budget Identifier narrative

xml/HumanitarianScopeVocabulary.xml
Update Humanitarian Plan URL to a user friendly version.
It has been confirmed that the new link is aligned to the source of the xml codelist.
=> Update Humanitarian Plan URL

xml/OrganisationRegistrationAgency.xml
Trying again, to refresh branch
https://github.com/IATI/IATI-Codelists-NonEmbedded/pull/252
https://github.com/IATI/IATI-Codelists-NonEmbedded/pull/254
=> Updates description for Org-ID codelist 

xml/IATIOrganisationIdentifier.xml
Adding XI-IATI-MIF to codelist, as per Discuss: https://discuss.iatistandard.org/t/approved-new-organisaton-identifier-xi-iati-mif/1346
=> Adding XI-IATI-MIF

xml/IATIOrganisationIdentifier.xml
Adding XI-IATI-FIABEL to codelist, as per Discuss: https://discuss.iatistandard.org/t/approved-create-new-organisation-identifier-xi-iati-fiabel/1283
=> Adding XI-IATI-FIABEL

xml/SectorVocabulary.xml
Adding NAICS to Sector Vocabulary Codelist, as per Discuss: https://discuss.iatistandard.org/t/approved-add-naics-to-sector-vocabulary-codelist/639/6
=> Adding NAICS Codelist

xml/Currency.xml
4 codes have been updated
USS - Dollar (Same day) has been removed
=> Update to ISO currency codelist

xml/IATIOrganisationIdentifier.xml
Adding two new organisations:
https://discuss.iatistandard.org/t/approved-request-for-new-org-id-xi-iati-ochasdc/1378
https://discuss.iatistandard.org/t/new-organisation-identifier-xi-iati-agr/1417
=> Add XI-IATI-AGR and XI-IATI-OCHASDC

xml/CollaborationType.xml
References IATI/IATI-Codelists#167.
=> Move codelist description from Budget Type

xml/BudgetIdentifierSector-category.xml
https://github.com/IATI/IATI-Extra-Documentation/issues/308
=> Budget Identifier Sector (category) - fixes typo

xml/Country.xml
=> Use ISO 3166 lower case short names for countries

xml/TagVocabulary.xml
Reverts IATI/IATI-Codelists-NonEmbedded#276, as [no consensus has been reached on when and how these should be added](https://github.com/IATI/IATI-Codelists-NonEmbedded/pull/276#issuecomment-444190087)
=> Revert "[Still in discussion] Adding SDG goals, targets, indicators to the TagVocabulary codelist"

xml/TagVocabulary.xml
=> Replacing broken URL for AGROVOC vocabulary

xml/IATIOrganisationIdentifier.xml
XI-IATI-ACATBA
https://discuss.iatistandard.org/t/new-organisation-identifier-xi-iati-acatba/1606
XI-IATI-BEH
https://discuss.iatistandard.org/t/new-organisation-identifier-xi-iati-beh/1598
=> Update XI-IATI list - two new entries

xml/IATIOrganisationIdentifier.xml
Adding two new entries to the XI-IATI list:
XI-IATI-LPI
https://discuss.iatistandard.org/t/approved-new-organization-identified-xi-iati-lpi/1619
XI-IATI-UDC
https://discuss.iatistandard.org/t/approved-new-organisation-identifier-xi-iati-udc/1625
=> Update XI-IATI Identifier list - LPI and UDC

xml/IATIOrganisationIdentifier.xml
Adding two new entries to the XI-IATI list:
XI-IATI-ATTIC: https://discuss.iatistandard.org/t/approved-new-organisation-identifier-xi-iati-attic/1655
XI-IATI-SGJ: https://discuss.iatistandard.org/t/approved-new-organisation-identifier-xi-iati-sgj/1650
=> Update to XI-IATI list - ATTIC and SGJ

xml/IATIOrganisationIdentifier.xml
Adding a new entry to the XI-IATI identifier list:
XI-IATI-EFRD: https://discuss.iatistandard.org/t/approved-new-organisation-identifier-xi-iati-efrd/1665
=> Update to XI-IATI list - EFRD

xml/IndicatorMeasure.xml
Updated version of an old [pull request](https://github.com/IATI/IATI-Codelists/pull/81)
=> Update description for Indicator Measure codelist

xml/DocumentCategory-category.xml
=> Adding Non-Core category to DocumentCategory-category.xml

xml/OrganisationType.xml
Link to Discuss post: https://discuss.iatistandard.org/t/bug-fix-incorrect-org-type-description/1755
Needs community sign off before merging
=> Update definition of org type 24 - Partner Country based NGO

xml/UNSDG-Goals.xml, xml/UNSDG-Targets.xml
=> Modify codelist category for SDG codelists

xml/CashandVoucherModalities
Adding the codelist following agreement on IATI Discuss: https://discuss.iatistandard.org/t/approved-proposal-to-add-cash-transfer-and-voucher-codelist-under-aid-type-vocabulary/1793
=> Create Cash and Voucher Modalities codelist

xml/IATIOrganisationIdentifier.xml
As per this post: https://discuss.iatistandard.org/t/approved-new-organisation-identifier-xi-iati-wbtf/1947
=> Add XI-IATI-WBTF

xml/SectorVocabulary.xml
Additional Sector Vocab added as per: https://iaticonnect.org/group/standard-management-consultations/discussion/approved-add-un-system-function-sector
=> Add UN System Function to Sector Vocab

xml/IATIOrganisationIdentifier.xml
Approved IATI Connect consultation: https://iaticonnect.org/group/standard-management-consultations-0/discussion/new-organisation-identifier-xi-iati-spr
=> New Organisation Identifier: XI-IATI-SPR

xml/CRSChannelCode.xml
[Trello](https://trello.com/c/pdN0plgF)
https://www.oecd.org/development/financing-sustainable-development/development-finance-standards/dacandcrscodelists.htm
https://webfs.oecd.org/crs-iati-xml/Lookup/DAC-CRS-CODES.xml﻿
=> OECD updates April 27 2021

xml/IATIOrganisationIdentifier.xml
Approved IATI Connect consultation: https://iaticonnect.org/group/standard-management-consultations-0/discussion/approved-new-organisation-identifier-xi-iati-5
=> New IATI Organisation Identifier - XI-IATI-NAGAAD

xml/AidType.xml, xml/CRSChannelCode.xml
[Trello](https://trello.com/c/wOz0JJPs)
=> DAC and CRS updates for 2022-01-21

xml/Currency.xml
Add new SLE currency code for Sierra Leone, issue nr: https://github.com/IATI/IATI-Codelists-NonEmbedded/issues/358
=> Add new SLE currency

xml/IATIOrganisationIdentifier.xml
Approved IATI Connect consultation: https://iaticonnect.org/group/standard-management-consultations-0/discussion/approved-new-organisation-identifier-xi-iati-6
=> New Organisational Identifier: XI-IATI-RUF

.github/workflows/CI.yml
[Trello](https://trello.com/c/tYdinKiA)
=> trigger IATI-Validator-Codelist workflows for all versions on push

.github/workflows/CI.yml, README.md
[Trello](https://trello.com/c/XCdAWKBU~)
=> Add trigger for dss filters workflow

xml/IATIOrganisationIdentifier.xml
https://iaticonnect.org/group/standard-management-consultations-0/discussion/new-organisation-identifier-xi-iati-1mc
=> Add XI-IATI-1MC for 1morecup to IATI Organisation Identifier list

xml/Region.xml
https://github.com/IATI/IATI-Codelists-NonEmbedded/issues/381
=> Sync Region name with OECD codelist

xml/Country.xml
Syrian Arab Republic -> Syrian Arab Republic (the)
Tanzania, United Republic of -> Tanzania, the United Republic of
Turkey -> Türkiye
=> Replicate country codelist names with latest ISO-3166

xml/IATIOrganisationIdentifier.xml
Approved IATI Connect consultation:
https://www.iaticonnect.org/group/standard-management-consultations-0/topic/new-organisation-identifier-xi-iati-khfifh
=> New Organisation Identifier: XI-IATI-KHF_IFH
